// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApixuTFIAdbyE28qPceBGAVIabjdPVTy0',
    appId: '1:776230994079:web:4d431a3f3f0a6ec2f222aa',
    messagingSenderId: '776230994079',
    projectId: 'alrahala-da896',
    authDomain: 'alrahala-da896.firebaseapp.com',
    storageBucket: 'alrahala-da896.firebasestorage.app',
    measurementId: 'G-0W3D6QSQNG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLu2a-j5oqMJkkCgjTAwQ5VP4qeYn_61o',
    appId: '1:776230994079:android:3cb63c8ebff30061f222aa',
    messagingSenderId: '776230994079',
    projectId: 'alrahala-da896',
    storageBucket: 'alrahala-da896.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBR8X200sJwcLxgw9Ere8-miFxFsLlMQBE',
    appId: '1:776230994079:ios:d0c7ec79f92fa40ff222aa',
    messagingSenderId: '776230994079',
    projectId: 'alrahala-da896',
    storageBucket: 'alrahala-da896.firebasestorage.app',
    iosBundleId: 'com.example.alrahalaCommecre',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBR8X200sJwcLxgw9Ere8-miFxFsLlMQBE',
    appId: '1:776230994079:ios:d0c7ec79f92fa40ff222aa',
    messagingSenderId: '776230994079',
    projectId: 'alrahala-da896',
    storageBucket: 'alrahala-da896.firebasestorage.app',
    iosBundleId: 'com.example.alrahalaCommecre',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyApixuTFIAdbyE28qPceBGAVIabjdPVTy0',
    appId: '1:776230994079:web:5ea421032547e8ddf222aa',
    messagingSenderId: '776230994079',
    projectId: 'alrahala-da896',
    authDomain: 'alrahala-da896.firebaseapp.com',
    storageBucket: 'alrahala-da896.firebasestorage.app',
    measurementId: 'G-1SJL0XGFD8',
  );

}